#!/bin/bash
# This script is used to upload the pyappm project to the web server downloads folder.

# Set the web server downloads folder path
web_server_download_folder="/inetpub/www/pyappm.nl/downloads"

# Set the pyappm project dist folder path
pyappm_project_dist_folder="dist"

# Set the pyappm project file name
pyappm_project_file_name="pyappm.zip"

# Set the web server user and ip address
web_server_user="root"
web_server_ip_address="10.32.1.5"

# Use SCP to upload the pyappm project to the web server downloads folder
scp -r $pyappm_project_dist_folder/$pyappm_project_file_name $web_server_user@$web_server_ip_address:$web_server_download_folder

# Set the pyappm installer file name and path
pyappm_installer_file_path="src/pyappm/installer.py"

# Use SCP to upload the installer to the web server downloads folder

#scp $pyappm_installer_file_path $web_server_user@$web_server_ip_address:$web_server_download_folder
